# Generated by Django 2.2.10 on 2020-05-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200527_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='options',
            field=models.ManyToManyField(help_text='Выбранные варианты', related_name='answers', to='polls.Option'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='owner_id',
            field=models.IntegerField(help_text='Уникальный ID владельца'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='vote_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата ответа'),
        ),
    ]
