# Generated by Django 2.2.10 on 2020-05-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200527_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='options',
            field=models.ManyToManyField(blank=True, help_text='Выбранные варианты', null=True, related_name='answers', to='polls.Option'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(blank=True, help_text='Текст ответа', null=True),
        ),
    ]
